### PR TITLE
integration golden file fix

### PR DESCRIPTION
**Pull request by witmicko**
**Describe what this PR does and why we need it**:
`get services -o=json` output has partial dynamic data that will vary between clusters. 
This PR adds a change that will strip that data both from expected and actual strings (output, golden file read), it does not modify golden file itself.

## Verification steps
1. [set up local cluster](https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/local-setup.adoc)
2. in mobile-cli run `make integration` -it should not FAIL
3. in mobile-core run `make clean`
4. repeat steps 1 and 2

### CODE REVIEW

**Comment by maleck13** [comment]
@witmicko this isn't currently passing for me

**Comment by witmicko** [comment]
@maleck13 are you running fresh cluster? my table output is different
```
+------------------------+---------------------+------------------+--------------------------------+----------------------------------+
|           ID           |        NAME         |   INTEGRATIONS   |           PARAMETERS           |              CLASS               |
+------------------------+---------------------+------------------+--------------------------------+----------------------------------+
| dh-unifiedpush-apb     | ups                 |                  | MYSQL_DATABASE,                | 1522a4d0e2fbf86a26cbe096eb1b6b2d |
|                        |                     |                  | MYSQL_PASSWORD,                |                                  |
|                        |                     |                  | MYSQL_ROOT_PASSWORD,           |                                  |
|                        |                     |                  | MYSQL_USER, MYSQL_VERSION      |                                  |
| dh-3scale-apb          | 3scale              |                  | THREESCALE_ACCESS_TOKEN,       | 2b825339e8d685a78476621a252beea8 |
|                        |                     |                  | THREESCALE_DOMAIN,             |                                  |
|                        |                     |                  | THREESCALE_ENABLE_CORS,        |                                  |
|                        |                     |                  | THREESCALE_SERVICE_ID          |                                  |
| dh-metrics-apb         | prometheus          |                  | GRAFANA_STORAGE_SIZE,          | 9623d53183cc78619f888ea8499c678e |
|                        |                     |                  | PROMETHEUS_STORAGE_SIZE        |                                  |
| dh-aerogear-digger-apb | aerogear-digger-apb |                  | ANDROID_LICENSE_AGREEMENT      | a0c0c2478554458d5c77abc95f0473a3 |
| dh-keycloak-apb        | keycloak            |                  | ADMIN_NAME, ADMIN_PASSWORD     | b95513950bb3f132de25d58fb75f8dca |
| dh-fh-sync-server-apb  | fh-sync-server      | keycloak,apiKeys | MONGODB_ADMIN_PASSWORD,        | c57e94c36c1e7f6bb41cf7c589d9eb08 |
|                        |                     |                  | MONGODB_USER_NAME,             |                                  |
|                        |                     |                  | MONGODB_USER_PASSWORD          |                                  |
+------------------------+---------------------+------------------+--------------------------------+----------------------------------+
```
this fix applied to json output so it seems to work fine

**Comment by dimitraz** [comment]
All steps work for me after the update :+1:

**Comment by maleck13** [comment]
all good

**Pull request merged**
