### PR TITLE
🔒 Require approval for PRs from untrusted sources

### PR DESCRIPTION
**Pull request by grdryn**
This initial step should not have any impact on PRs from people who
are members of the aerogear org, or for non-PR builds from this
Jenkinsfile.

For contributors who are not members of the aerogear org, PRs will
hang at this step, waiting for someone to approve. Only people who can
authenticate to the Jenkins instance will be able to approve --
currently that means 'members of the fheng org'.

This is intended as a safety measure to help prevent potential attacks
on our build infrastructure, by executing arbitrary code there through
pull requests.

### CODE REVIEW

**Comment by maleck13** [comment]
@grdryn how do we approve them? Also could you add a doc change to the CONTRIBUTING guide to reflect this change

**Comment by grdryn** [comment]
> how do we approve them?

The build will be triggered as normal, and will have a link here (it'll have the yellow circle status indicating that the build is 'in progress' rather than the green tick or red X). Clicking the link will bring you to the build in Jenkins where you can login and hit 'Approve' or 'Reject'. Once this is merged, I'll submit a PR from an untrusted account to show you.

The idea is that the change would get a look over by a trusted person before the job being run by an untrusted user.

Note that PRs from external contributors which have changes to the Jenkinsfile will not be built using that changed Jenkinsfile, but rather the Jenkinsfile as it was before they changed it. That's a little confusing in my opinion, but it safeguards against someone untrusted submitting a malicious change and bypassing the trust stage by removing it from the Jenkinsfile.

> Also could you add a doc change to the CONTRIBUTING guide to reflect this change

Sure, will do. 👍

**Comment by grdryn** [comment]
@maleck13 is that change to the contributing guide enough?

@AdamSaleh if you're adding a Jenkinsfile to any other repos, could you include a trust stage like this?

**Comment by maleck13** [comment]
@philbrookes @witmicko @JameelB @aidenkeating Making you guys aware of this change.

@grdryn I think it would make sense to send a mail out to the mailing list regarding this change, just so it is communicated to the whole team who may find themselves reviewing an external PR at some point. This is where I meant to put this comment :)

**Pull request merged**
